plugins {
    // https://maven.fabricmc.net/net/fabricmc/fabric-loom/net.fabricmc.fabric-loom.gradle.plugin/maven-metadata.xml
    id 'net.fabricmc.fabric-loom' version '1.17.21' apply false
    // https://projects.neoforged.net/neoforged/moddevgradle
    id 'net.neoforged.moddev' version '2.0.148' apply false
}
